#pragma once

#define KEYPAD_ON_SOUND E__NOTE(_A4), E__NOTE(_B4),
#define KEYPAD_OFF_SOUND E__NOTE(_B4), E__NOTE(_A4),

#define THUMB_WIN_SOUND E__NOTE(_GS5), E__NOTE(_A5), S__NOTE(_REST), E__NOTE(_E6), E__NOTE(_D6),
#define THUMB_MAC_SOUND E__NOTE(_GS5), E__NOTE(_A5), S__NOTE(_REST), E__NOTE(_GS5), E__NOTE(_A6),
#define THUMB_PC_SOUND E__NOTE(_GS5), E__NOTE(_A5), S__NOTE(_REST), Q__NOTE(_D6),
